apiVersion: v2
name: pihole
description: A Helm chart for Pi-hole deployment in Kubernetes
type: application
version: 0.2.3
sources:
- https://github.com/abufazal/charts/
- https://github.com/abufazal/charts/pihole
dependencies:
  - name: common
    version: 2.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
maintainers:
- email: abbas0013@gmail.com
  name: Abu Fazal Abbas
  url: https://github.com/abufazal
icon: https://upload.wikimedia.org/wikipedia/commons/0/00/Pi-hole_Logo.png  
appVersion: "latest"
