apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  {{- if not .Values.pihole.deployment.autoscaling.enabled }}
    {{- if .Values.pihole.persistence.enabled }}
  replicas: {{ .Values.pihole.deployment.replicas }}
    {{- else }}
  replicas: 1
    {{- end }}
  {{- else }}
    {{- if not .Values.pihole.persistence.enabled }}
  replicas: 1
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pihole.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.pihole.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pihole.labels" . | nindent 8 }}
        {{- with .Values.pihole.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec: 
      {{- with .Values.pihole.image.pullSecrets }}
      imagePullSecrets: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pihole.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.pihole.deployment.podSecurityContext | nindent 8 }}
      containers:        
        - name: {{ .Chart.Name }}
          env:
            - name: TZ
              value: {{ default "Asia/Kolkata" .Values.pihole.timeZone | quote }}
            - name: TEMPERATUREUNIT
              value: {{ default "c" .Values.pihole.dashboard.temperatureUnit | quote }}
            - name: QUERY_LOGGING
              value: {{ default true .Values.pihole.queryLogging | quote }}
            - name: WEBUIBOXEDLAYOUT
              value: {{ default true .Values.pihole.dashboard.boxedLayout | ternary "boxed" "traditional" | quote }}
            - name: WEBTHEME
              value: {{ default "default-auto" .Values.pihole.dashboard.theme | quote }}
            - name: WEBPASSWORD_FILE
              valueFrom:
                secretKeyRef:
                  name: {{ include "pihole.adminSecret" . }}
                  key: webpassword
            - name: PIHOLE_DNS_
              value: {{ default (list "1.1.1.1" "1.1.1.2") .Values.pihole.upstream | join ";" | quote }}
            - name: DNSSEC
              value: {{ default true .Values.pihole.dnssec.enabled | quote }}
            - name: DNS_BOGUS_PRIV
              value: {{ default false .Values.pihole.privateRangeForwarding.enabled  | ternary "false" "true" | quote }}
            - name: DNS_FQDN_REQUIRED
              value: {{ default true .Values.pihole.requiredFqdn | quote }}
            - name: REV_SERVER
              value: {{ default false .Values.pihole.reverseServer.enabled | quote }}
            {{- if .Values.pihole.reverseServer.enabled -}}
            - name: REV_SERVER_DOMAIN
              value: {{ .Values.pihole.reverseServer.domain | quote }}
            - name: REV_SERVER_TARGET
              value: {{ .Values.pihole.reverseServer.target | quote }}  
            - name: REV_SERVER_CIDR
              value: {{ .Values.pihole.reverseServer.cidr | quote }}
            {{- end }}
          securityContext:
            {{- if .Values.pihole.deployment.securityContext }}
            capabilities:
              {{- if not .Values.pihole.deployment.securityContext.capabilities }}
              add:
                - NET_ADMIN
              {{- else }}
              add:
                {{- $defaultCapabilities := list "NET_ADMIN" }}
                {{- $additionalCapabilities := .Values.pihole.deployment.securityContext.capabilities.add | default (list) }}
                {{- range $capability := $defaultCapabilities }}
                - {{ $capability }}
                {{- end }}
                {{- range $capability := $additionalCapabilities }}
                  {{- if ne $capability "NET_ADMIN" }}
                - {{ $capability }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- range $key, $value := .Values.pihole.deployment.securityContext }}
              {{- if ne $key "capabilities" }}
            {{ $key }}: {{ if kindIs "map" $value }}{{ toYaml $value | nindent 14 }}{{ else }}{{ $value | quote }}{{ end }}
              {{- end }}
            {{- end }}  
          {{- else }}
            capabilities:
              add:
                - NET_ADMIN
            {{- end }}
          image: {{ include "pihole.image" . }}
          imagePullPolicy: {{ .Values.pihole.image.pullPolicy }}
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dhcp
              containerPort: 67
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP                    
          livenessProbe:
            {{- toYaml .Values.pihole.deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.pihole.deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.pihole.deployment.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.pihole.deployment.volumeMounts }}
            {{- toYaml .Values.pihole.deployment.volumeMounts | nindent 12 }}
            {{- end }}
            {{- if .Values.pihole.persistence.enabled }}
            - name: pvc-etc
              mountPath: /etc/pihole
            - name: pvc-dnsmasq
              mountPath: /etc/dnsmasq.d
            {{- end }}
      volumes:
        {{- if .Values.pihole.deployment.volumes }}
        {{- toYaml .Values.pihole.deployment.volumes | nindent 8 }}
        {{- end }}
        {{- if .Values.pihole.persistence.enabled }}
        - name: pvc-etc
          persistentVolumeClaim:
            claimName: {{ include "pihole.dataPVCName" . }}
        - name: pvc-dnsmasq
          persistentVolumeClaim:
            claimName: {{ include "pihole.dnsmasqPVCName" . }}
        {{- end }}
      {{- with .Values.pihole.deployment.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pihole.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pihole.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pihole.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
