apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.dnsServiceName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: {{ include "pihole.dnsExternalTrafficPolicy" . }}
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dhcp
      port: 67
      protocol: UDP
      targetPort: 67
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}
  {{- if .Values.pihole.services.dns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.pihole.services.dns.loadBalancerIP | quote }}
  {{- end }}
