{{- if and .Values.pihole.deployment.autoscaling.enabled .Values.pihole.persistence.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pihole.fullname" . }}
  minReplicas: {{ default 1 .Values.pihole.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ default 3 .Values.pihole.deployment.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ default 80 .Values.pihole.deployment.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ default 80 .Values.pihole.deployment.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
