{{- if and .Values.pihole.deployment.autoscaling.enabled .Values.pihole.persistence.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pihole.fullname" . }}
  minReplicas: {{ default 1 .Values.pihole.deployment.autoscaling.minReplicas }}
  maxReplicas: {{ default 3 .Values.pihole.deployment.autoscaling.maxReplicas }}
  metrics:
    {{- range $resource := (list "cpu" "memory") }}
    - type: Resource
      resource:
        name: {{ $resource }}
        target:
          type: Utilization
          averageUtilization: {{ default 80 (index .Values.pihole.deployment.autoscaling (printf "target%sUtilizationPercentage" (camelcase $resource))) }}
    {{- end }}
{{- end }}
