{{- if .Values.pihole.deployment.ingress.enabled }}
{{- if and .Values.pihole.deployment.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.pihole.deployment.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.pihole.deployment.ingress.annotations "kubernetes.io/ingress.class" .Values.pihole.deployment.ingress.ingressClassName }}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pihole.ingressName" }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.pihole.deployment.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if .Values.pihole.deployment.ingress.secureBackends }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.pihole.deployment.ingress.ingressClassName }}
  ingressClassName: {{ .Values.pihole.deployment.ingress.ingressClassName }}
  {{- end }}
  rules:
  - host: {{ .Values.pihole.deployment.ingress.host }}
    http:
      paths:
        - path: {{ default "/admin" .Values.pihole.deployment.ingress.path }}
          pathType: {{ default "ImplementationSpecific" .Values.pihole.deployment.ingress.pathType }}
          backend:
            service:
              name: {{ include "pihole.adminServiceName" . }}
              port:
                number: 80
{{- if .Values.pihole.deployment.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.pihole.deployment.ingress.host }}
    secretName: {{ .Values.pihole.deployment.ingress.tlsSecret }}
{{- end }}
{{- end }}
