{{- if .Values.ingressRoute.enabled }}
  {{- if .Values.ingressRoute.className }}
    {{- if not (hasKey .Values.ingressRoute.annotations "kubernetes.io/ingress.class") }}
    {{- $_ := set .Values.ingressRoute.annotations "kubernetes.io/ingress.class" .Values.ingressRoute.className }}
    {{- end }}
  {{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "pihole.ingressRouteName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.ingressRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: {{ include "pihole.ingressRoute" . }}
      kind: Rule
      services:
        - name: {{ include "pihole.adminServiceName" . }}
          namespace: {{ .Release.Namespace }}
          port: 80
  {{- if and (not (empty .Values.ingressRoute.domain.cert.issuer.name)) (not (empty .Values.ingressRoute.domain.cert.issuer.type)) }}
  tls:
    secretName: {{ include "pihole.domainCertSecretName" . }}
  {{- end }}
{{- end }}
