{{- $enablePersistence := default false .Values.pihole.persistence.enabled }}

{{- if $enablePersistence }}
{{- if not .Values.pihole.persistence.data.existingClaimName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.dataPVCName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.pihole.persistence.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ required "Error - Storage class name is required for data volume" .Values.pihole.persistence.data.storageClassName }}
  resources:
    requests:
      storage: {{ default "4Gi" .Values.pihole.persistence.data.size }}
{{- end }}

{{- if not .Values.pihole.persistence.dnsmasq.existingClaimName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pihole.dnsmasqPVCName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.pihole.persistence.keep }}
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ required "Error - Storage class name is required for dnsmasq volume" .Values.pihole.persistence.dnsmasq.storageClassName }}
  resources:
    requests:
      storage: {{ default "100Mi" .Values.pihole.persistence.dnsmasq.size }}      
{{- end }}      

{{- end }}
