{{- if (empty .Values.pihole.dashboard.admin.passwordSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.adminSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (empty .Values.pihole.dashboard.admin.password) }}
  webpassword: {{ randAlphaNum 16 | b64enc | quote }}
  {{- else }}
  webpassword: {{ .Values.pihole.dashboard.admin.password }}
  {{- end }}
{{- end }}  
