{{- if .Values.pihole.deployment.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pihole.serviceAccountName" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.pihole.deployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.pihole.deployment.serviceAccount.automount | default "true" }}
{{- end }}
